#!/usr/bin/env python3
"""Generate a Resolve DCTL for a source/reference still pair.

The generated DCTL applies a global OKLab mean-and-standard-deviation transfer.
It must be used on linear Rec.709/sRGB-primaries RGB values (for example, after
an input CST that outputs Linear Rec.709).  It is intentionally a static look:
analyse one representative source still, then apply the result to matching shots.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

try:
    import numpy as np
    from PIL import Image
except ImportError as exc:
    raise SystemExit(
        "Missing dependency. Install with: python3 -m pip install numpy Pillow\n"
        f"Details: {exc}"
    )


EPSILON = 1e-5


def srgb_to_linear(rgb: np.ndarray) -> np.ndarray:
    return np.where(rgb <= 0.04045, rgb / 12.92, ((rgb + 0.055) / 1.055) ** 2.4)


def linear_rgb_to_oklab(rgb: np.ndarray) -> np.ndarray:
    """Convert an (..., 3) linear sRGB / Rec.709 array to OKLab."""
    lms = rgb @ np.array(
        [[0.4122214708, 0.2119034982, 0.0883024619],
         [0.5363325363, 0.6806995451, 0.2817188376],
         [0.0514459929, 0.1073969566, 0.6299787005]], dtype=np.float64
    )
    lms_cuberoot = np.cbrt(lms)
    return lms_cuberoot @ np.array(
        [[0.2104542553, 1.9779984951, 0.0259040371],
         [0.7936177850, -2.4285922050, 0.7827717662],
         [-0.0040720468, 0.4505937099, -0.8086757660]], dtype=np.float64
    )


def load_oklab(path: Path, sample_limit: int) -> np.ndarray:
    with Image.open(path) as image:
        image = image.convert("RGB")
        if image.width * image.height > sample_limit:
            scale = math.sqrt(sample_limit / (image.width * image.height))
            size = (max(1, round(image.width * scale)), max(1, round(image.height * scale)))
            image = image.resize(size, Image.Resampling.BOX)
        rgb = np.asarray(image, dtype=np.float64) / 255.0
    return linear_rgb_to_oklab(srgb_to_linear(rgb)).reshape(-1, 3)


def load_group_oklab(paths: list[Path], sample_limit: int) -> np.ndarray:
    """Load a group with approximately equal per-image sample allowance."""
    per_image_limit = max(1, sample_limit // len(paths))
    return np.concatenate([load_oklab(path, per_image_limit) for path in paths], axis=0)


def fmt(value: float) -> str:
    return f"{value:.9f}f"


PROFILE_MACROS = {
    "mix": "PROFILE_MIX",
    "shadows": "PROFILE_SHADOWS",
    "midtones": "PROFILE_MIDTONES",
    "highlights": "PROFILE_HIGHLIGHTS",
    "highlight_protect": "PROFILE_HIGHLIGHT_PROTECT",
    "warm_protect": "PROFILE_WARM_PROTECT",
    "hue_rotate": "PROFILE_HUE_ROTATE",
    "chroma": "PROFILE_CHROMA",
}


def dctl_text(source_mean: np.ndarray, source_std: np.ndarray,
              target_mean: np.ndarray, target_std: np.ndarray, *, defaults: dict[str, float] | None = None,
              profile_header: bool = False) -> str:
    defaults = defaults or {}
    def default(name: str, fallback: float) -> str:
        if profile_header:
            return PROFILE_MACROS[name]
        return f"{float(defaults.get(name, fallback)):.3f}"
    values = {
        "SRC_L": source_mean[0], "SRC_A": source_mean[1], "SRC_B": source_mean[2],
        "SRC_STD_L": source_std[0], "SRC_STD_A": source_std[1], "SRC_STD_B": source_std[2],
        "TGT_L": target_mean[0], "TGT_A": target_mean[1], "TGT_B": target_mean[2],
        "TGT_STD_L": target_std[0], "TGT_STD_A": target_std[1], "TGT_STD_B": target_std[2],
    }
    constants = ('#include "ReferenceMatchProfile.h"' if profile_header else
                 "\n".join(f"__CONSTANT__ float {name} = {fmt(value)};" for name, value in values.items()))
    input_default = "PROFILE_INPUT_ENCODING" if profile_header else "1"
    generated_by = "Reference Match Bridge" if profile_header else "generate_reference_transfer_dctl.py"
    return f"""// Generated by generate_reference_transfer_dctl.py
// INPUT CONTRACT
//   sRGB JPEG PNG: display-referred JPEG/PNG, decoded and re-encoded internally.
//   Linear Rec709: already-linear Rec.709/sRGB primaries from an upstream CST.
// PIPELINE
//   input decode -> OKLab statistical transfer -> hue/chroma vector match
//   -> highlight/warm protection -> output encode.
// VIEW MODES
//   Result: final pipeline; Base Transfer: before vector matching; Vector Match:
//   after hue/chroma; Protect Mask: red=highlight, green=warm; Difference: change map.
// This is a static look calibrated to the supplied source still and reference still.

// Engine mode: {generated_by}

{constants}

DEFINE_UI_PARAMS(inputEncoding, Input Encoding, DCTLUI_COMBO_BOX, {input_default}, {{ LINEAR, SRGB }}, {{ Linear Rec709, sRGB JPEG PNG }})
DEFINE_UI_PARAMS(viewMode, View, DCTLUI_COMBO_BOX, 0, {{ RESULT, BASE_TRANSFER, VECTOR_MATCH, PROTECT_MASK, DIFFERENCE }}, {{ Result, Base Transfer, Vector Match, Protect Mask, Difference }})
DEFINE_UI_PARAMS(mixAmount, Mix, DCTLUI_SLIDER_FLOAT, {default("mix", .75)}, 0.0, 1.0, 0.01)
DEFINE_UI_PARAMS(shadowStrength, Shadows, DCTLUI_SLIDER_FLOAT, {default("shadows", 1)}, 0.0, 1.5, 0.01)
DEFINE_UI_PARAMS(midStrength, Midtones, DCTLUI_SLIDER_FLOAT, {default("midtones", 1)}, 0.0, 1.5, 0.01)
DEFINE_UI_PARAMS(highStrength, Highlights, DCTLUI_SLIDER_FLOAT, {default("highlights", 1)}, 0.0, 1.5, 0.01)
DEFINE_UI_PARAMS(highProtect, Highlight Protect, DCTLUI_SLIDER_FLOAT, {default("highlight_protect", .5)}, 0.0, 1.0, 0.01)
DEFINE_UI_PARAMS(warmProtect, Warm Tone Protect, DCTLUI_SLIDER_FLOAT, {default("warm_protect", .25)}, 0.0, 1.0, 0.01)
DEFINE_UI_PARAMS(hueRotate, Hue Rotate, DCTLUI_SLIDER_FLOAT, {default("hue_rotate", 8)}, -30.0, 30.0, 0.1)
DEFINE_UI_PARAMS(chromaScale, Chroma, DCTLUI_SLIDER_FLOAT, {default("chroma", .85)}, 0.0, 2.0, 0.01)

__DEVICE__ float smoothStep(float edge0, float edge1, float value)
{{
    const float t = _saturatef((value - edge0) / (edge1 - edge0));
    return t * t * (3.0f - 2.0f * t);
}}

__DEVICE__ float signedCbrt(float value)
{{
    return _copysignf(_powf(_fabs(value), 0.333333333f), value);
}}

__DEVICE__ float srgbToLinear(float value)
{{
    return value <= 0.04045f ? value / 12.92f : _powf((value + 0.055f) / 1.055f, 2.4f);
}}

__DEVICE__ float linearToSrgb(float value)
{{
    const float signedValue = _copysignf(value, value);
    const float magnitude = _fabs(value);
    const float encoded = magnitude <= 0.0031308f ? magnitude * 12.92f : 1.055f * _powf(magnitude, 1.0f / 2.4f) - 0.055f;
    return signedValue < 0.0f ? -encoded : encoded;
}}

__DEVICE__ float3 linearRgbToOklab(float3 rgb)
{{
    const float l = signedCbrt(0.4122214708f * rgb.x + 0.5363325363f * rgb.y + 0.0514459929f * rgb.z);
    const float m = signedCbrt(0.2119034982f * rgb.x + 0.6806995451f * rgb.y + 0.1073969566f * rgb.z);
    const float s = signedCbrt(0.0883024619f * rgb.x + 0.2817188376f * rgb.y + 0.6299787005f * rgb.z);
    return make_float3(
        0.2104542553f * l + 0.7936177850f * m - 0.0040720468f * s,
        1.9779984951f * l - 2.4285922050f * m + 0.4505937099f * s,
        0.0259040371f * l + 0.7827717662f * m - 0.8086757660f * s);
}}

__DEVICE__ float3 oklabToLinearRgb(float3 lab)
{{
    const float l = lab.x + 0.3963377774f * lab.y + 0.2158037573f * lab.z;
    const float m = lab.x - 0.1055613458f * lab.y - 0.0638541728f * lab.z;
    const float s = lab.x - 0.0894841775f * lab.y - 1.2914855480f * lab.z;
    const float l3 = l * l * l;
    const float m3 = m * m * m;
    const float s3 = s * s * s;
    return make_float3(
         4.0767416621f * l3 - 3.3077115913f * m3 + 0.2309699292f * s3,
        -1.2684380046f * l3 + 2.6097574011f * m3 - 0.3413193965f * s3,
        -0.0041960863f * l3 - 0.7034186147f * m3 + 1.7076147010f * s3);
}}

__DEVICE__ float3 transform(int p_Width, int p_Height, int p_X, int p_Y, float p_R, float p_G, float p_B)
{{
    const float3 original = make_float3(p_R, p_G, p_B);
    float3 working = original;
    if (inputEncoding == SRGB)
    {{
        working.x = srgbToLinear(working.x);
        working.y = srgbToLinear(working.y);
        working.z = srgbToLinear(working.z);
    }}
    const float3 lab = linearRgbToOklab(working);
    float3 mapped;
    mapped.x = ((lab.x - SRC_L) / SRC_STD_L) * TGT_STD_L + TGT_L;
    mapped.y = ((lab.y - SRC_A) / SRC_STD_A) * TGT_STD_A + TGT_A;
    mapped.z = ((lab.z - SRC_B) / SRC_STD_B) * TGT_STD_B + TGT_B;
    const float3 baseMapped = mapped;

    // Fine vector-scope alignment in the perceptual OKLab a/b plane.
    const float hueRadians = hueRotate * 0.0174532925f;
    const float mappedA = mapped.y * chromaScale;
    const float mappedB = mapped.z * chromaScale;
    mapped.y = _cosf(hueRadians) * mappedA - _sinf(hueRadians) * mappedB;
    mapped.z = _sinf(hueRadians) * mappedA + _cosf(hueRadians) * mappedB;

    const float shadowWeight = 1.0f - smoothStep(0.20f, 0.45f, lab.x);
    const float highWeight = smoothStep(0.55f, 0.85f, lab.x);
    const float midWeight = _fminf(1.0f - shadowWeight, 1.0f - highWeight);
    const float tonalStrength = shadowWeight * shadowStrength + midWeight * midStrength + highWeight * highStrength;

    // Approximate warm/skin-region protection, not semantic skin detection.
    const float warmAxis = _saturatef((lab.y * 0.85f + lab.z * 0.35f + 0.025f) / 0.10f);
    const float chroma = _sqrtf(lab.y * lab.y + lab.z * lab.z);
    const float warmMask = warmAxis * smoothStep(0.025f, 0.060f, chroma) * (1.0f - highWeight);
    const float protectedMix = mixAmount * tonalStrength * (1.0f - highProtect * highWeight) * (1.0f - warmProtect * warmMask);

    const float3 baseTransferred = oklabToLinearRgb(baseMapped);
    const float3 transferred = oklabToLinearRgb(mapped);
    if (viewMode == BASE_TRANSFER)
        return inputEncoding == SRGB ? make_float3(linearToSrgb(baseTransferred.x), linearToSrgb(baseTransferred.y), linearToSrgb(baseTransferred.z)) : baseTransferred;
    if (viewMode == VECTOR_MATCH)
        return inputEncoding == SRGB ? make_float3(linearToSrgb(transferred.x), linearToSrgb(transferred.y), linearToSrgb(transferred.z)) : transferred;
    if (viewMode == PROTECT_MASK)
        return make_float3(highWeight, warmMask, 0.0f);
    if (viewMode == DIFFERENCE)
        return make_float3(_fabs(transferred.x - working.x) * 4.0f, _fabs(transferred.y - working.y) * 4.0f, _fabs(transferred.z - working.z) * 4.0f);

    float3 result = _mix(working, transferred, _saturatef(protectedMix));
    if (inputEncoding == SRGB)
        result = make_float3(linearToSrgb(result.x), linearToSrgb(result.y), linearToSrgb(result.z));
    return result;
}}
"""


def generic_engine_text() -> str:
    """Return the stable DCTL engine that consumes ReferenceMatchProfile.h."""
    zeros = np.zeros(3, dtype=np.float64)
    ones = np.ones(3, dtype=np.float64)
    return dctl_text(zeros, ones, zeros, ones, profile_header=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an OKLab reference-transfer DCTL.")
    parser.add_argument("source", type=Path, help="Representative source still (sRGB/Rec.709 image)")
    parser.add_argument("reference", type=Path, help="Reference still (sRGB/Rec.709 image)")
    parser.add_argument("--extra-source", type=Path, action="append", default=[],
                        help="Additional matching source still; may be repeated")
    parser.add_argument("--extra-reference", type=Path, action="append", default=[],
                        help="Additional reference still; may be repeated")
    parser.add_argument("--output", type=Path, default=Path("Reference_Transfer_OKLab.dctl"))
    parser.add_argument("--stats", type=Path, default=None, help="Optional JSON statistics output")
    parser.add_argument("--sample-limit", type=int, default=1_000_000)
    parser.add_argument("--mix", type=float, default=.75)
    parser.add_argument("--shadows", type=float, default=1.)
    parser.add_argument("--midtones", type=float, default=1.)
    parser.add_argument("--highlights", type=float, default=1.)
    parser.add_argument("--highlight-protect", type=float, default=.5)
    parser.add_argument("--warm-protect", type=float, default=.25)
    parser.add_argument("--hue-rotate", type=float, default=8.)
    parser.add_argument("--chroma", type=float, default=.85)
    args = parser.parse_args()

    if args.sample_limit < 1:
        parser.error("--sample-limit must be positive")
    source_paths = [args.source, *args.extra_source]
    reference_paths = [args.reference, *args.extra_reference]
    for path in [*source_paths, *reference_paths]:
        if not path.is_file():
            parser.error(f"File not found: {path}")

    source = load_group_oklab(source_paths, args.sample_limit)
    reference = load_group_oklab(reference_paths, args.sample_limit)
    source_mean, target_mean = source.mean(axis=0), reference.mean(axis=0)
    source_std = np.maximum(source.std(axis=0), EPSILON)
    target_std = np.maximum(reference.std(axis=0), EPSILON)

    defaults = {
        "mix": args.mix, "shadows": args.shadows, "midtones": args.midtones,
        "highlights": args.highlights, "highlight_protect": args.highlight_protect,
        "warm_protect": args.warm_protect, "hue_rotate": args.hue_rotate, "chroma": args.chroma,
    }
    args.output.write_text(dctl_text(source_mean, source_std, target_mean, target_std, defaults=defaults), encoding="utf-8")
    stats_path = args.stats or args.output.with_suffix(".json")
    stats_path.write_text(json.dumps({
        "algorithm": "OKLab channel-wise mean and standard-deviation transfer",
        "source_files": [str(path) for path in source_paths],
        "reference_files": [str(path) for path in reference_paths],
        "source_mean": source_mean.tolist(), "source_std": source_std.tolist(),
        "reference_mean": target_mean.tolist(), "reference_std": target_std.tolist(),
        "input_contract": "source and reference files are interpreted as display-referred sRGB/Rec.709; generated DCTL expects linear Rec.709/sRGB primaries",
        "dctl_defaults": defaults,
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote DCTL:  {args.output}")
    print(f"Wrote stats: {stats_path}")


if __name__ == "__main__":
    main()
